name: HitThruPlants
author: PulsePvP_
main: pulsepvp_.hitthruplants.Main
version: 1.3.2
description: Hit entities through plants.
prefix:

commands:
  htp:
    description: Main command 
    usage: /htp
